### ISSUE TITLE
error: ACPI table bigger than 64KB (VERR_TOO_MUCH_DATA)

### ISSUE THREAD

**Issue by ft44k** [nsmfoo/antivmdetection#11]
Hi Mikael,

I got no luck to get it running, already tried 2 machines with the same result (one of those is old Lenovo R500). The size of generated DSDT table is not larger than the 64KB (62806 bytes) and still virtualbox refuses to run the session (virtualbox 5.1 on ubuntu 16.04, tried also older versions of both with the same result)

https://dl.dropboxusercontent.com/u/31835862/DSDT.zip

I followed instructions from this article
https://byte-atlas.blogspot.sk/2017/02/hardening-vbox-win7x64.html

Please let me know if you need anything else

**Comment by nsmfoo** [comment]
Hi Jaroslav,

The error message is a bit confusing, the size is for all ACPI tables and not only the DSDT.

https://www.virtualbox.org/ticket/15043

So if you fancy, please bug the VBox devs and/or try to find more hardware. Old Dell laptops are often fine. 

I hope you find suitable hardware soon, also if you run into any other issues please let me know! 

Regards
Mikael

**Comment by redpath-intel** [comment]
@ft44k,

This is a proposed workaround and it may come with some caveats (still testing them myself.) I wound up downloading MaciASL (An ACPI Editor) and downloaded a DSDT file from https://www.tonymacx86.com/dsdt-database

Once downloaded, I saved the DSDT file in binary format, modified the .sh script to point to the new DSDT file and was able to continue. 

They have a few DSDT files, but only 1 for a laptop. It would be cool to see about seeing if we can add a directory for default profiles'n whatnot. I got a lenovo at home I could pull info from.

Anyhow, hope that helps!

##UPDATE:
Yeah... that didn't seem to help at all unfortunately, back to the drawing board!

**Comment by nsmfoo** [comment]
The idea to have a repository is not bad at all. But given that the rest of the information that is collected to build the profile will not match, in the same way as if all data is collected from the same system.  I think it is time to approach  the VBox devs again on the subject, as the limit will become more of an issue going forward. My suggestion is to take a Ubuntu live-cd and walk around the neighborhood until you find and semi-old laptop and generate a profile from that machine. No need to re-install the OS, just boot and install the needed dependencies and copy the profile files to an USB device.

**Comment by nsmfoo** [comment]
I will close this one. And yes, It will most likely come back again soon. 

Going forward, I believe that this issue needs to be fixed, fixed in Virtualbox, so bug your local VBox dev to get it done =)
