### ISSUE TITLE
hdparm -I outputs errors -> gets shoved in script.

### ISSUE THREAD

**Issue by redpath-intel** [nsmfoo/antivmdetection#12]
All,

I have an interesting setup on my Mac El Capitan:
VMWare Fusion Running an Ubuntu Image
Virtualbox running inside the Ubuntu Image

When running the hardening script, I would get an error showing that the firmware revision was longer than 8 bytes. After looking at the script, I was able to google and see that the issue stemmed from hdparm outputting:
"""
/dev/sda:
SG_IO: bad/missing sense data, sb[]: Byte stream longer than 8 bytes
"""

This information gets shoved into the script and ultimately assigned to the VM.

To correct this, I manually modified the script and added the following parameters (from an old google post):
Set SerialNumber to: "AD3C0845CB6C452CBB30"
FirmwareRevision to: "FC2ZF50B"
ModelNumber to: "HITACHI HTD723216L9SA60"
SerialNumber to: "091118FC1221NCJ6G8GG"

For port firmware revision... i used the same value again with no complaints. I'm not very knowledgable about what these parameters may affect, but perhaps we can add a check to generate some random BS if an error is detected?

**Comment by nsmfoo** [comment]
Hi, 
Yes that make sense, to catch the error and replace it with something else.
But first, I will try to mimic your setup, give me a few days. Would be nice with a generic solution with real data

**Comment by nsmfoo** [comment]
If no one complains, I had the time to think a bit (first time for everything) and I will add a check for a none existing value. But that's about it. 

In general it's better for you or people with a similar setup, to find an old computer and generate the template using that hardware. It will look a lot more plausible, macOS + Fusion + Ubuntu will not expose the same information as  proper hardware + OS installation, hence the template will not be as valuable as a real one.

**Comment by nsmfoo** [comment]
Closed with the release of 0.1.8
