### ISSUE TITLE
AttributeError: 'module' object has no attribute 'bios'

### ISSUE THREAD

**Issue by psylinux** [nsmfoo/antivmdetection#13]
==[ Error:
sudo python antivmdetect.py 
--- Generate VirtualBox templates to help thwart VM detection and more .. - Mikael, @nsmfoo ---
[*] Creating VirtualBox modifications ..
Traceback (most recent call last):
  File "antivmdetect.py", line 46, in <module>
    dmi_info['DmiBIOSReleaseDate'] = v['data']['Relase Date']
NameError: name 'v' is not defined

==[ Debbuging Info

$ python -V
Python 2.7.12

$ virtualbox -h
Oracle VM VirtualBox Manager 5.0.32_Ubuntu
(C) 2005-2017 Oracle Corporation
All rights reserved.

sudo dmidecode -V
3.0

$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18.1 Serena
Release:	18.1
Codename:	serena

$ sudo dpkg -l python-dmidecode libcdio-utils acpidump mesa-utils
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                 Version                 Architecture            Description
ii  acpidump                             20160108-2              all                     transitional dummy package
ii  libcdio-utils                        0.83-4.2ubuntu1         amd64                   sample applications based on the CDIO libraries
ii  mesa-utils                           8.3.0-1                 amd64                   Miscellaneous Mesa GL utilities
ii  python-dmidecode                     3.12.2-2                amd64                   Python extension module for dmidecode

processor	: 7
vendor_id	: GenuineIntel
cpu family	: 6
model		: 58
model name	: Intel(R) Core(TM) i7-3632QM CPU @ **2.20GHz**

**Comment by nsmfoo** [comment]
Hi, sorry for my late reply! 

The error is generated because the script is unable to retrieve the BIOS release date.

If you are able, please paste the full output of:  dmidecode.bios().values(). 

Just add a  'print v'  below line 121

**Comment by nebriv** [comment]
Hey Mikael,

I'm having the same problem I think.

I added the following line:

```
+print dmidecode.bios().values()

try:
   for v in dmidecode.bios().values():
```

Which results in:

--- Generate VirtualBox templates to help thwart VM detection and more .. - Mikael, @nsmfoo ---
[*] Creating VirtualBox modifications ..
Traceback (most recent call last):
  File "antivmdetect.py", line 39, in <module>
    print dmidecode.bios().values()
AttributeError: 'module' object has no attribute 'bios'

It looks like dmidecode is not picking up the BIOS information from the system?

test.py = dmidecode.profile()
```
/antivmdetection$ python test.py 
Dell Inc. OptiPlex 9020 (SN: DN****, UUID: 4C4C4544-****-****-****-*********)
Intel Core i5 3800 MHz (Core: 4, Thead: 4)
2 memory stick(s), 8192 MB in total
```

**Comment by nsmfoo** [comment]
@psylinux coming back to your issue. I might have an idea. But first are you able to run: dmidecode -t0 and give me the output?

**Comment by nsmfoo** [comment]
@nebriv Hi Ben!

https://github.com/nsmfoo/antivmdetection/issues/2  the issue do look similar?

It could be a python issue. If you run dmidecode -t0 from the command line. Do you seem any information?

Did you install python-dmidecode via apt or via pip (version?)? 

Also if you can give me your OS/distribution version

**Comment by nebriv** [comment]
Yup! Looks very similar. I think I installed dmidecode through apt. I'm running Ubuntu 14.04 Desktop. I would suspect it's due to version differences? What version of dmidecode do you have working?

Heres the output from dmidecode -t0:
```
~$ sudo !!
sudo dmidecode -t0
# dmidecode 2.12
SMBIOS 2.7 present.

Handle 0x0000, DMI type 0, 24 bytes
BIOS Information
	Vendor: Dell Inc.
	Version: A07
	Release Date: 04/25/2014
	Address: 0xF0000
	Runtime Size: 64 kB
	ROM Size: 12288 kB
	Characteristics:
		PCI is supported
		PNP is supported
		BIOS is upgradeable
		BIOS shadowing is allowed
		Boot from CD is supported
		Selectable boot is supported
		EDD is supported
		5.25"/1.2 MB floppy services are supported (int 13h)
		3.5"/720 kB floppy services are supported (int 13h)
		3.5"/2.88 MB floppy services are supported (int 13h)
		Print screen service is supported (int 5h)
		8042 keyboard services are supported (int 9h)
		Serial services are supported (int 14h)
		Printer services are supported (int 17h)
		ACPI is supported
		USB legacy is supported
		BIOS boot specification is supported
		Function key-initiated network boot is supported
		Targeted content distribution is supported
		UEFI is supported
	BIOS Revision: 4.6
```

**Comment by nsmfoo** [comment]
It does (normally) work with Ubuntu 14.04 and/or 16.04. 

Which version of python-dmidecode do you have installed?

**Comment by nsmfoo** [comment]
@nebriv I installed an Ubuntu 14.04 Desktop on an old Dell machine and it works Using python-dmidecode 3.10.13-3, can you verify that you were using the same version?

**Comment by nebriv** [comment]
Got it figured out! Apparently I had accidentally installed it with pip (which uses version .08 or something absurd) AND apt... Completely removed it and installed it with apt and it works perfectly.

Thanks for your help!

**Comment by nsmfoo** [comment]
@nebriv great that you got it working! I will go a head and close this case. Please let me know if you have any other questions.

@psylinux as I think you had the same/similar issue, please try to do as @nebriv  did. If that does not resolve the issue, please re-open this case
