### ISSUE TITLE
VM fails to start

### ISSUE THREAD

**Issue by Dhatheway** [nsmfoo/antivmdetection#15]
The .sh files runs with no errors, but when I try to start the VM in order to install the OS I get the following message "Error: failed to start machine. Error message: PIIX3 configuration error: "FirmwareRevision" is longer than 8 bytes (VERR_INVALID_PARAMETER)"

Maybe errors in the .sh file:
VBoxManage setextradata "$1" VBoxInternal/Devices/pcbios/0/Config/DmiSystemVendor       'Dell Inc.'
VBoxManage setextradata "$1" VBoxInternal/Devices/pcbios/0/Config/DmiSystemVersion      'string:'
controller=`VBoxManage showvminfo "$1" --machinereadable | grep SATA`
if [[ -z "$controller" ]]; then
VBoxManage setextradata "$1" VBoxInternal/Devices/piix3ide/0/Config/PrimaryMaster/ModelNumber   'SG_IO: bad/missing sense data, sb[]:  70 00 05 00 00 00 00 0d 00 00 00 00 20 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
 HDIO_GET_IDENTITY failed: Invalid argument'
VBoxManage setextradata "$1" VBoxInternal/Devices/piix3ide/0/Config/PrimaryMaster/SerialNumber  '4016140B3A674D9BAA4A'

Ubuntu 16.04.2 LTS
python-dmidecode 3.12.2-2
python 2.7.12
virtualbox 5.1.22r115126

**Comment by nsmfoo** [comment]
Hi @Dhatheway I will look into it during the weekend and get back to you

**Comment by nsmfoo** [comment]
@Dhatheway Are you by any chance, using a virtual linux installation running on top of macOS to generate the profile?

**Comment by nsmfoo** [comment]
Regardless, try the new 0.1.8 release and let me know if you run into any issues related to your report or any new ones, because of it =)

**Comment by Dhatheway** [comment]
Nope just Ubuntu 16.04.2 LTS installed on a Dell server. I'll try out the new version in the morning and let you know thanks again for the help.

**Comment by nsmfoo** [comment]
Ok, then it must be the DELL raid. As native support is much better and if you feel up for it. 
Please send me the output of something similar to this: smartctl -d <device type> -i /dev/<device> or if you can retrieve the needed information using some DELL supplied tool, that will work as well. 

You can mask any sensitive information, like the serial number

**Comment by Dhatheway** [comment]
Sorry for my late reply, after using the new version all works well. Still getting a few detection's via pafish, but as for the build its working flawless.
 

[pafish] Start
[pafish] Windows version: 6.1 build 7601
[pafish] CPU: GenuineIntel Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz       
[pafish] CPU VM traced by checking the difference between CPU timestamp counters (rdtsc)
[pafish] CPU VM traced by checking the difference between CPU timestamp counters (rdtsc) forcing VM exit
[pafish] Hooks traced using ShellExecuteExW method 1
[pafish] VirtualBox device identifiers traced using WMI
[pafish] End

**Comment by nsmfoo** [comment]
@Dhatheway regarding the artefacts that still left.

> [pafish] CPU VM traced by checking the difference between CPU timestamp counters (rdtsc)
>[pafish] CPU VM traced by checking the difference between CPU timestamp counters (rdtsc) forcing
They are not covered today 

> [pafish] Hooks traced using ShellExecuteExW method 1
Did you run pafish manually on clean system or did you run it Cuckoo for example?

> [pafish] VirtualBox device identifiers traced using WMI
This indicates that the powershell script has not be successfully executed, can you share more information about the target system(OS)? Also please note that WMI and some registry settings re-surface after reboot. So you need to run the powershell script once again

**Comment by Dhatheway** [comment]
I swear I read the instructions :P ran the PS1 file again and all is well thanks again for all your help!

**Comment by nsmfoo** [comment]
I believe you! The process is a bit messy and confusing at times =). I'm glad that you got it to work! If you run into any other strange things, just let me know!
