### ISSUE TITLE
Non-booting VM after running AllSeries.sh

### ISSUE THREAD

**Issue by DigiAngel** [nsmfoo/antivmdetection#17]
Here's the errors I receive:
~~~
VBoxManage: error: The VM session was aborted
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component SessionMachine, interface ISession
~~~
and from the log:
~~~
Untrusted device called trusted helper! 'ahci'/0
~~~

Any hints on getting this to work?  Thank you.

**Comment by DigiAngel** [comment]
Well I've whittled this down to here:
~~~
<ExtraDataItem name="VBoxInternal/Devices/acpi/0/Config/CustomTable" value="DSDT_AllSeries.bin"/>
      <ExtraDataItem name="VBoxInternal/Devices/ahci/0/Config/Port0/FirmwareRevision" value="EXM02B6Q"/>
      <ExtraDataItem name="VBoxInternal/Devices/ahci/0/Config/Port0/ModelNumber" value="Samsung SSD 850 PRO 256GB"/>
      <ExtraDataItem name="VBoxInternal/Devices/ahci/0/Config/Port0/SerialNumber" value="0F8D9A0C4ABD44B"/>
      <ExtraDataItem name="VBoxInternal/Devices/ahci/0/Config/Port1/ATAPIProductId" value="BDDVDW SE-506AB"/>
      <ExtraDataItem name="VBoxInternal/Devices/ahci/0/Config/Port1/ATAPIRevision" value="TS00"/>
      <ExtraDataItem name="VBoxInternal/Devices/ahci/0/Config/Port1/ATAPISerialNumber" value="<snip>"/>
      <ExtraDataItem name="VBoxInternal/Devices/ahci/0/Config/Port1/ATAPIVendorId" value="TSSTcorp"/>
~~~

If I remove this section the VM boots...so i'm at a loss on what to do next.  Thank you

**Comment by nsmfoo** [comment]
Hi @DigiAngel just to get some background information, the OS you created the template on and arch? Also are you trying to apply the template on a XP guest? If so, that's no longer supported. You can check out an earlier version that supported XP. Otherwise it could be that you have devices connected to both port 0 and port 1.  From the top of my head, I think only port 0 is "supported" for hard drives.. if that does not solve the issue, let me get back to you tomorrow(ish)

**Comment by DigiAngel** [comment]
Ah bugger ya..I was just messing with this on XP.  I'll spin up a Win7 and report my findings...thanks for the response and great work!

**Comment by DigiAngel** [comment]
Ok...so my AllSeries.sh run looked like this:
~~~
AllSeries.sh: 40: AllSeries.sh: [[: not found
AllSeries.sh: 49: AllSeries.sh: [[: not found
AllSeries.sh: 82: [: 172.16.0.1: unexpected operator
AllSeries.sh: 84: [: default: unexpected operator
AllSeries.sh: 86: [: pulse: unexpected operator
~~~

After fixing the DmiBIOSVersion issue, I now have this:
~~~
Waiting for VM "Win7 Analysis" to power on...
VBoxManage: error: Error: ACPI tables bigger than 64KB (VERR_TOO_MUCH_DATA)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole
~~~

And that's where I'm at :)  Guessing it has something to do with this:
~~~
[WARNING] Size of the DSDT file is too large (> 64k). Try to build the template from another computer
~~~
This is on the latest VBox on linux.  Thank you.

**Comment by nsmfoo** [comment]
The size issue is known and it's actually not my fault, it's a limitation in VirtualBox =)
For reference: https://github.com/nsmfoo/antivmdetection/issues/11 

My suggestion is that you boot a random (older) laptop or computer with a Ubuntu Live-CD and try to run the template on that machine.

Regarding the other errors in the shell script. Do you get these from a clean run, or have you made manual changes to the file? If so that may be the case.

**Comment by DigiAngel** [comment]
Thanks for the responses on this...and of course, VB is the challenge sometimes ;)  I have older boxes around so I'll try and get a good DSDT file.  The log entries above are from a clean run, no changes to files.  I'll get an older box, run, and report here..thank you!

**Comment by DigiAngel** [comment]
Ok here we go :)  Found an old imac running Ubuntu 16.04 Desktop.  First up, initial run:
~~~
--- Generate VirtualBox templates to help thwart VM detection and more .. - Mikael, @nsmfoo ---
[*] Creating VirtualBox modifications ..
[*] Creating a DSDT file...
[*] Finished: A template shell script has been created named: iMac9,1.sh
[*] Finished: A DSDT dump has been created named: DSDT_iMac9,1.bin
[*] Creating guest based modification file (to be run inside the guest)...
[WARNING] Unable to retrieve correct information! You are probably using a server distribution. Will add some semi correct data ... 
[Info] Could not find a user supplied file called: clipboard_buffer, a random string will be generated instead
[*] Finished: A Powershell file has been created, named: iMac9,1.ps1
~~~

Next up, the sh run:
~~~
iMac9,1.sh: 40: iMac9,1.sh: [[: not found
iMac9,1.sh: 49: iMac9,1.sh: [[: not found
iMac9,1.sh: 82: [: 172.16.0.1: unexpected operator
iMac9,1.sh: 84: [: default: unexpected operator
iMac9,1.sh: 86: [: pulse: unexpected operator
iMac9,1.sh: 89: [: !=: argument expected
~~~

First VM run:
VBoxManage: error: Configuration error: Querying "DmiChassisType" as an int failed (VERR_CFGM_NOT_INTEGER)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole
~~~
Was set to "none", changed it to "256".  Last bit was to change the name and locale of the "DSDT_iMac9,1.bin" since the comma in the name through the whole thing off.  Now it's working well...thank you!

**Comment by nsmfoo** [comment]
You are using very exotic hardware, but I'm glad that it worked out. Will add the comma issue and the ChassisType to my todo list. The values retrieved depends very much on the hardware, Apple hardware has not been look at that much. Please let me know if you run into any other issue!
