### ISSUE TITLE
PIIX3 configuration error

### ISSUE THREAD

**Issue by devwhatsapp** [nsmfoo/antivmdetection#18]
Virtualbox error- 

`PIIX3 configuration error: "FirmwareRevision" is longer than 8 bytes (VERR_INVALID_PARAMETER).`

sh file error - 

```
VBoxManage setextradata "$1" VBoxInternal/Devices/piix3ide/0/Config/PrimaryMaster/ModelNumber	' HDIO_GET_IDENTITY failed: Invalid argument'
VBoxManage setextradata "$1" VBoxInternal/Devices/piix3ide/0/Config/PrimaryMaster/FirmwareRevision	' HDIO_GET_IDENTITY failed: Invalid argument'
else
VBoxManage setextradata "$1" VBoxInternal/Devices/ahci/0/Config/Port0/ModelNumber	' HDIO_GET_IDENTITY failed: Invalid argument'
VBoxManage setextradata "$1" VBoxInternal/Devices/ahci/0/Config/Port0/FirmwareRevision	' HDIO_GET_IDENTITY failed: Invalid argument'
fi
```
python-dmidecode 3.12.2-2
python 2.7.12
Virtualbox 5.1.22 r115126 (Qt5.5.1)
elementary OS 0.4.1 Loki
antivmdetection -from git

**Comment by nsmfoo** [comment]
Hi @devwhatsapp Let's see if I can help you out.

What type of hardware are you using? (Server with RAID etc)

I did resolve a similar issue in the latest release:
https://github.com/nsmfoo/antivmdetection/issues/15

**Comment by devwhatsapp** [comment]
Home PC
Gigabyte motherboard
HDD Samsung

**Comment by nsmfoo** [comment]
Late reply, busy celebrating midsummer =)
So, do you have a device called /dev/sda ? If so what does the output of the following command give you: hdparm -i /dev/sda ?

**Comment by devwhatsapp** [comment]
No issues , we should always celebrate whats need to

Output of hdparm -i /dev/sda

/dev/sda:
 HDIO_GET_IDENTITY failed: Invalid argument

**Comment by devwhatsapp** [comment]
Found the culprit.

It was an external HDD which was connected and taking the place of /dev/sda

Now removed it and the script works.

You can add this info to check for such a problem.

Thank you

**Comment by nsmfoo** [comment]
Great that you were able to solve the issue! 
I will look into it, if there is a nifty way to create such a check I will add it.

If you run into any other issues or have questions, just let me know!
