### ISSUE TITLE
AcpiCreatorRev Error

### ISSUE THREAD

**Issue by devwhatsapp** [nsmfoo/antivmdetection#19]
Hi new error 

> Configuration error: Querying "AcpiCreatorRev" as integer failed (VERR_CFGM_NOT_INTEGER).

in .sh script-
VBoxManage setextradata "$1" VBoxInternal/Devices/acpi/0/Config/AcpiOemId	'ALASKA'
VBoxManage setextradata "$1" VBoxInternal/Devices/acpi/0/Config/AcpiCreatorId	'string:I'
VBoxManage setextradata "$1" VBoxInternal/Devices/acpi/0/Config/AcpiCreatorRev	'00000088'

**Comment by devwhatsapp** [comment]
I changed

> VBoxManage setextradata "$1" VBoxInternal/Devices/acpi/0/Config/AcpiCreatorRev '00000088'

to

>  VBoxManage setextradata "$1" VBoxInternal/Devices/acpi/0/Config/AcpiCreatorRev '00000001'

it boots , but will it effect the detection or any other problem ?

Whats the correct solution ?

**Comment by nsmfoo** [comment]
Some or most vendors that I have come across uses the date like: <year><month><day> for the AcpiCreatorRev. You motherboard seems to use a number series, but it should work as well...

The error comes from VirtualBox, so it might be a bug. But I will look at it and get back to you
(https://www.virtualbox.org/svn/vbox/trunk/src/VBox/Devices/PC/DevACPI.cpp)

The "correct" solution is that the collected data works, but I don't see that it increases the detection in any way, the attacker needs to know the correct value to be able to spot the difference.

**Comment by devwhatsapp** [comment]
Okay thank you , I will continue using with the value modified.
