### ISSUE TITLE
Bios problem

### ISSUE THREAD

**Issue by seifreed** [nsmfoo/antivmdetection#2]
--- Generate VirtualBox templates to help thwart vm detection - Mikael, @nsmfoo ---
[*] Creating VirtualBox modifications ..
Traceback (most recent call last):
  File "antivmdetect.py", line 34, in <module>
    for v in dmidecode.bios().values():
AttributeError: 'module' object has no attribute 'bios'

**Comment by nsmfoo** [comment]
Hi,

Are you able to run: sudo dmidecode -t 0? Also could you add a ''print dmidecode.bios().values()' and send me the output?

**Comment by seifreed** [comment]
Hi,

Here you go:

seifreed@linux-analyzer:~/Descargas$  sudo dmidecode -t 0
[sudo] password for seifreed:

# dmidecode 2.12

SMBIOS 2.7 present.

Handle 0x0000, DMI type 0, 24 bytes
BIOS Information
    Vendor: Phoenix Technologies LTD
    Version: 6.00
    Release Date: 07/02/2015
    Address: 0xEA5E0
    Runtime Size: 88608 bytes
    ROM Size: 64 kB
    Characteristics:
        ISA is supported
        PCI is supported
        PC Card (PCMCIA) is supported
        PNP is supported
        APM is supported
        BIOS is upgradeable
        BIOS shadowing is allowed
        ESCD support is available
        Boot from CD is supported
        Selectable boot is supported
        EDD is supported
        Print screen service is supported (int 5h)
        8042 keyboard services are supported (int 9h)
        Serial services are supported (int 14h)
        Printer services are supported (int 17h)
        CGA/mono video services are supported (int 10h)
        ACPI is supported
        Smart battery is supported
        BIOS boot specification is supported
        Function key-initiated network boot is supported
        Targeted content distribution is supported
    BIOS Revision: 4.6
    Firmware Revision: 0.0

## Regards,

Marc Rivero López | @seifreed | www.ecrime.info http://www.ecrime.info/

**Comment by nsmfoo** [comment]
Sorry, two more questions:
- Which version of python-dmidecode do you have installed?
- Also could you add a: print dmidecode.bios().values() to row 35

**Comment by seifreed** [comment]
Hi,

Here you go!

seifreed@linux-analyzer:~/Descargas$ dpkg -l python-dmidecode
Deseado=Desconocido/Instalar/Eliminar/Purgar/Retener
| Estado=No/Instalado/Config-files/Desempaquetado/Medio-conf/Medio-inst/espera-disparo/pendiente-disparo
|/ Err?=(ninguno)/Requiere-reinst (Estado,Err: mayúsc.=malo)
||/ Nombre                                       Versión                     Arquitectura                Descripción
+++-============================================-===========================-===========================-==============================================================================================
ii  python-dmidecode                             3.10.13-3                   amd64                       Python extension module for dmidecode
seifreed@linux-analyzer:~/Descargas$

I changed the code:

But is not showing nothing :-(

## Regards,

Marc Rivero López | @seifreed | www.ecrime.info http://www.ecrime.info/

**Comment by nsmfoo** [comment]
Great thanks for the information! Will take a closer look at it later tonight.

**Comment by seifreed** [comment]
Hi,

Thanks man!

## Best regards!

Marc Rivero López | @seifreed | www.ecrime.info http://www.ecrime.info/

**Comment by nsmfoo** [comment]
Hi,

Sorry for my late reply!

Not the best response, but here are some options
- Try to run the script on some other hardware, possible newer (ISA port? =)), just to see that it _do_ work normally ;)
- On the host, verify if python-dmidecode contains the BIOS module.
  -> python
  -> import dmidecode
  -> dir (dmidecode), is "bios" in the list?
- If not, try to remove python-dmidecode (apt-get and/or pip uninstall) and then re-install it again. Any change?

**Comment by seifreed** [comment]
Hi,

Look:

seifreed@linux-analyzer:~/tools/malware/antivmdetection$ dpkg -l python-dmidecode
Deseado=Desconocido/Instalar/Eliminar/Purgar/Retener
| Estado=No/Instalado/Config-files/Desempaquetado/Medio-conf/Medio-inst/espera-disparo/pendiente-disparo
|/ Err?=(ninguno)/Requiere-reinst (Estado,Err: mayúsc.=malo)
||/ Nombre                                       Versión                     Arquitectura                Descripción
+++-============================================-===========================-===========================-==============================================================================================
ii  python-dmidecode                             3.10.13-3                   amd64                       Python extension module for dmidecode
seifreed@linux-analyzer:~/tools/malware/antivmdetection$ python
Python 2.7.11 (default, Jan 29 2016, 11:14:37)
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import dmidecode
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > ImportError: No module named dmidecode

## Regards,

Marc Rivero López | @seifreed | www.ecrime.info http://www.ecrime.info/

**Comment by nsmfoo** [comment]
Hi,

It looks to be installed, yes. Is it possible that you also installed it via PIP? 
You should be able to import the module "by hand" doing the above.

My suggestion is to removed the package all together (apt-get remove/purge and via PIP), search in the filesystem to verify. Then install it again.

I hope this helps

/Mikael

**Comment by seifreed** [comment]
Hi,

## Seems, is not working :-(

Marc Rivero López | @seifreed | www.ecrime.info http://www.ecrime.info/

**Comment by nsmfoo** [comment]
Can you follow me back on Twitter? Makes for quicker responses from my side. I'm sure we can solve this issue somehow =)

**Comment by nsmfoo** [comment]
Hi again Marc,

As there is no new feedback, I will go a head and close this ticket. Feel free to drop me an email or re-open the case if you have more information to share.
