### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by jessstoner** [nsmfoo/antivmdetection#22]
ola, need some help for run dis on win10(host)
already have almost finished patch. Im tryin to finish it maself, but in pafish some markers r still red
need some help
@jessstoner telegram
boozt3@gmail.com 
i can pay for ur service.

**Comment by nsmfoo** [comment]
Hi,
I do this for free so no need for paying me. But to be able to better understand which issues you are having. Could you please let me know what issues are still detected?  For example CPU timestamp is an issue that I have not been able to solve without making changes to Virtualbox itself.

**Comment by jessstoner** [comment]
hi. thx for answer.
![tcxotie](https://user-images.githubusercontent.com/32709788/31612795-6dd2e1d4-b29a-11e7-91c4-9bd4659f4763.png)

**Comment by jessstoner** [comment]
p.s
have only 6gb ram and 120gb SSD
do u have any idea how to change gpu?

**Comment by nsmfoo** [comment]
Hi, 

Sorry for my late reply!

So too focus on the attached picture: 

- The first detection, is sadly not resolved with the script. It's a bit outside of my scripts scope, but it can be done with other solutions 
-  The detection of the disk size if pretty straight forward, if you have disk space make the image bigger, currently the script as it's rather "simple" can't fake disk size
- Number of processors, you most likely are able to add one or several more to your guest, that would solve that alert
- Uptime detection, is easy to resolve. Just let the image run for a while and re-run the test and you should be OK. If you take a snapshot you can always manage this detection method.

I hope this was answers to your questions, if not please let me know!

**Comment by nsmfoo** [comment]
Regarding change GPU. I have not put that much effort into it. But a starting point would perhaps be to look at VBox support for PCI passthrough,https://www.virtualbox.org/manual/ch09.html#pcipassthrough

**Comment by nsmfoo** [comment]
I will go a head and close this issue. Feel free to re-open or create a new one if you more questions
