### ISSUE TITLE
bash outside vm script not running

### ISSUE THREAD

**Issue by me0ne0** [nsmfoo/antivmdetection#26]
hi, i m trying to use your script to make my vm detection hard. So far it generates the required scripts as follows, but when i try to execute outside script, it gives me error "too many arguments on line 72". when i sudo run the script, it gives me error of "win7x642 vm not found" while in the list list it clearly detects the said vm. Can you please help me resolve this error?

mxn@mxn-Latitude-E6510:~/antivmdetection$ sudo python antivmdetect.py 
--- Generate VirtualBox templates to help thwart VM detection and more .. - Mikael, @nsmfoo ---
[*] Creating VirtualBox modifications ..
[*] Creating a DSDT file...
[*] Finished: A template shell script has been created named: LatitudeE6510.sh
[*] Finished: A DSDT dump has been created named: DSDT_LatitudeE6510.bin
[*] Creating guest based modification file (to be run inside the guest)...
[Info] Could not find a user supplied file called: clipboard_buffer, a random string will be generated instead
[*] Finished: A Powershell file has been created, named: LatitudeE6510.ps1

mxn@mxn-Latitude-E6510:~/antivmdetection$ bash ./LatitudeE6510.sh
[*] Please add vm name!
[*] Available vms:
win7x64-VB
win7x642
mxn@mxn-Latitude-E6510:~/antivmdetection$ bash ./LatitudeE6510.sh win7x642
./LatitudeE6510.sh: line 72: [: too many arguments

mxn@mxn-Latitude-E6510:~/antivmdetection$ sudo bash ./LatitudeE6510.sh win7x642
VBoxManage: error: Could not find a registered machine named 'win7x642'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports

**Comment by vladbrinzea** [comment]
Hi me0ne0, just a plain user like yourself here offering an opinion. Have you tried running the LatitudeE6510.sh script without sudo? Sounds to me like it may be that you're getting that error because the virtual machine is registered to a different user than root...

**Comment by me0ne0** [comment]
hello vladbrinzea, well as i mentioned earlier, i tried running both commands. with and without sudo. with sudo it gives error "VBoxManage: error: Could not find a registered machine named 'win7x642'" and without sudo it gives error "./LatitudeE6510.sh: line 72: [: too many arguments"
when i try to run without bash, it gives me following error
mxn@mxn-Latitude-E6510:~/antivmdetection$ ./LatitudeE6510.sh win7x642
bash: ./LatitudeE6510.sh: Permission denied


I tried googling the error but its of no help.

**Comment by nsmfoo** [comment]
Hi sorry for the delay, I can set aside some time on Wednesday to hopefully resolve this issue =)

**Comment by me0ne0** [comment]
@nsmfoo No problem for late replying (i was actually looking for your twitter to ping you but could not find it) and thank you mikael for taking time to look at it, looking forward to your positive response.

**Comment by me0ne0** [comment]
@nsmfoo hello, did u get chance to look at the error ?

**Comment by nsmfoo** [comment]
Hi sorry, spare time started now =)

In general you should not need to run the script with sudo, run the script using the user who have access to VirtualBox. Try running: VBoxManage list vms, the user who has vm's is the correct user.

Regarding the script error, which OS are you using? (possible also shell version)
Are you only seeing the error or do you get other output as well?

Are you able to share the row 72? I'm seeing some other error on another row which confuses me a bit

and you should be able to find me on twitter @nsmfoo =)

**Comment by nsmfoo** [comment]
my issue was with the "audio" row, if that matches your issue, change the corresponding row to look like this: 

"audio=$(VBoxManage showvminfo --machinereadable "$1" | grep audio | cut -d "=" -f2 | sed 's/"//g' | head -1)"

Apparently things have changed ... 

I will push this fix in a few days, if it's not your issue please let me know =)

**Comment by me0ne0** [comment]
Hi, i am using ubuntu 16.04.4 LTS and bash shell version is 4.3.48(1)-release

as far as i can check.. the line in the script is

if [ $hostint_ip == '192.168.56.1' ]; then echo "[WARNING] You are using the default IP/IP-range. Consider changing the IP and the range used!"; fi

**Comment by me0ne0** [comment]
let me check the audio issue as pointed out by you

**Comment by me0ne0** [comment]
i am just seeing the error... ./LatitudeE6510.sh: line 72: [: too many arguments

**Comment by me0ne0** [comment]
@nsmfoo hello ... any update?

**Comment by nsmfoo** [comment]
@me0ne0 Hi, can you give me the output of the following command?

VBoxManage list hostonlyifs | grep IPAddress: | awk {' print $2 '}

**Comment by me0ne0** [comment]
hi mikael, sorry for replying so late. i was out of town. heres the output.. I am using 192.168.56.1 as vboxnet0 and 10.10.10.1 as vboxnet1

(cuckoo) mxn@mxn-Latitude-E6510:~$ VBoxManage list hostonlyifs | grep IPAddres | awk {' print $2 '}
192.168.77.1
192.168.59.1
192.168.82.1
192.168.66.1
192.168.81.1
192.168.70.1
192.168.60.1
192.168.58.1
10.10.10.1
192.168.80.1
192.168.75.1
192.168.71.1
192.168.73.1
192.168.85.1
192.168.88.1
192.168.86.1
192.168.61.1
192.168.69.1
192.168.83.1
192.168.68.1
192.168.87.1
192.168.84.1
192.168.56.1
192.168.63.1
192.168.65.1
192.168.76.1
192.168.67.1
192.168.79.1
192.168.72.1
192.168.78.1
192.168.74.1
192.168.64.1
192.168.62.1

**Comment by me0ne0** [comment]
Damn its a long list. Can i disable any of the subnets that i dont intend to use? :/

**Comment by me0ne0** [comment]
you can focus on 192.168.56.1

**Comment by nsmfoo** [comment]
@me0ne0 try the latest version, I "might" have added a workaround for your issue. Let me know if it works or not

**Comment by me0ne0** [comment]
hello mikael. I pulled the new commit and gave it a try. I am now continuously getting the following error.
--------------------------------------------------------------
mxn@mxn-Latitude-E6510:~/antivmdetection$ bash ./LatitudeE6510.sh win7x643
[WARNING] You are using the default IP/IP-range. Consider changing the IP and the range used!
---------------------------------------------------------------

I just created a new empty guest vm. did not install ISO yet. Network Adapter has been changed to "vboxnet1" with ip 10.10.10.1.. I tried to run it on different VM's the error is same.


vboxnet0  Link encap:Ethernet  HWaddr 0a:00:27:00:00:00  
          inet addr:192.168.56.1  Bcast:192.168.56.255  Mask:255.255.255.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

vboxnet1  Link encap:Ethernet  HWaddr 0a:00:27:00:00:01  
          inet addr:10.10.10.1  Bcast:10.10.10.255  Mask:255.255.255.0
          inet6 addr: fe80::800:27ff:fe00:1/64 Scope:Link
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:17657 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:3450074 (3.4 MB)

Is this issue being caused as voboxnet0 is active along with vboxnet1? Should i disable vboxnet0 and check?

**Comment by me0ne0** [comment]
as i configured 2 vboxnets i was under the impression the script would check for the one mentioned in the network settings of the guest VM. Anyways, it checks for default ip 192.168.56.1 and if found in any vboxnet it will generate a warning. 

Now i have changed the ip scheme and warning is gone. Outside script runs successfully. Next to check inside VM script. Hopefully it will work too :-) i shall update later

**Comment by me0ne0** [comment]
alright :-) script works like a charm. Thankyou @nsmfoo for your time to write the changes and updating the antivmdetection.py 

However, Just out of context question, do you know a way to fix these errors as generated by pafish. I know you have mentioned that your script works otherthan pafish but i thought you might shed some light on it.

CPU VM traced by checking the difference between CPU timstamp counters (rdtsc)
CPU VM traced by checking the difference between CPU timstamp counters (rdtsc) forcing
Sandbox traced using mouse activity
Sandbox traced by checking operating system uptime using GetTickCount()
VirtualBox traced using reg key HKLM\HARDWARE\Description\System "VideoBiosVersion"
VirtualBox traced using reg key HKLM\HARDWARE\ACPI\DSDT\VBOX__
VirtualBox traced using reg key HKLM\HARDWARE\Description\System "SystemBiosVersion"
VirtualBox device identifiers traced using WMI

**Comment by me0ne0** [comment]
i got 2 errors of ACPI while running in the Guest VM script via power shell

**Comment by me0ne0** [comment]
![screenshot from 2018-04-19 16-59-08](https://user-images.githubusercontent.com/28728882/38990309-25caa03a-43f3-11e8-810b-ab21f16d9b2a.png)

**Comment by nsmfoo** [comment]
@me0ne0 It was a good idea, I will improve the check to match it agains the target VM. Sometimes during next week or so .. 

Regarding the pafish alerts:

- CPU VM traced by checking the difference between CPU timstamp counters (rdtsc)
- CPU VM traced by checking the difference between CPU timstamp counters (rdtsc) forcing

These two are not mitigated by my script, as I have not yet figured out a way to do so. That being said it's not the best VM check so it can give FP's on none VM's as well.

- Sandbox traced using mouse activity
This check looks for mouse movements during the pafish run. For example if you move the mouse during the time the check is running you will have "evaded it". If you plan to use your VM for manual infection, this is most likely not an issue. If you plan to use Cuckoo for example, there is a built in function to perform the same movements.

- Sandbox traced by checking operating system uptime using GetTickCount()
This check, looks at the uptime of the VM. So either let your VM run for a while and re-run, this is also a smart move to make snapshop of a VM that is been running for a while.

- VirtualBox traced using reg key HKLM\HARDWARE\Description\System "VideoBiosVersion"
- VirtualBox traced using reg key HKLM\HARDWARE\ACPI\DSDT\VBOX__
- VirtualBox traced using reg key HKLM\HARDWARE\Description\System "SystemBiosVersion"
These should have been removed, after the reboot. Did you re-run the script again?

- VirtualBox device identifiers traced using WMI
This indicates that the usage of  DevManView.exe might not have worked as expected, can you verify that you are using the correct version, in your case I believe it's 64-bit ?  Also this might be linked to the above

**Comment by nsmfoo** [comment]
Regarding the other error, let's see if we can resolve the first things, the second error might very well depend on the first issues

**Comment by me0ne0** [comment]
i will give it a try again.

**Comment by nsmfoo** [comment]
@me0ne0 did you have time to try the above?

**Comment by nsmfoo** [comment]
@me0ne0 I have added the feature that you suggested. Will be pushed soon. As I assume that you have everything working I will close this case, feel free to re-open if needed
