### ISSUE TITLE
Dependencies Warning Getting Warning Message For Computer.lst and User.lst

### ISSUE THREAD

**Issue by seantree** [nsmfoo/antivmdetection#29]
Hi,

I am getting a warning message for Computer.lst and User.lst
.

I have Centos 7 Has a Host machine & Windows 7 VM (Virtualbox) has a guest machine
.
I am running antivmdetection.py in centos 7 and getting the warning message for Computer.lst & User.lst dependencies.
.
How to fix these dependencies issue.
.
Thanks & Regards
Seantree

**Comment by nsmfoo** [comment]
Hi, 
late reply, as noted in the code but not well documented.

"# Requires a file with a list of "computer"(host) names - A start would be to use a list from this site: http://www.outpost9.com/files/WordLists.html"

"# Requires a file with a list of "usernames" - A start would be to use a list from this site: http://www.outpost9.com/files/WordLists.html"

So create two files, one with suitable hostnames and the other with similar usernames in the same path as the script.

I hope this helps, if not please let me know

/Mikael
