### ISSUE TITLE
KVM Detection?

### ISSUE THREAD

**Issue by nahaye** [nsmfoo/antivmdetection#30]
good stuff , but it will be better in other arquitectures, not only in VBOX, are you working on that? or thinking in that improvement?

Best Regards

**Comment by nsmfoo** [comment]
Yes it would,  I might look into making this script available for other architecture.  But for now there is this great guide for KVM: https://www.doomedraven.com/2016/05/kvm.html (it's updated just recently). 

That being said the second part of my script that is being run inside the guest can be used on any architectures.

**Comment by nsmfoo** [comment]
I will close this case for now, if you have any follow questions please let me know
