### ISSUE TITLE
How to fix the dependencies on archlinux?

### ISSUE THREAD

**Issue by corechip** [nsmfoo/antivmdetection#31]
It seems some of the dependencies are not available on archlinux. How to fix them and use this script on archlinux?

**Comment by AVJoKe** [comment]
Install python-dmidecode from AUR, pip2 install dmidecode and install the package acpica with pacman (contains acpidump)

**Comment by nsmfoo** [comment]
I only test the script using Ubuntu, but if you got it to work with the help of @AVJoKe suggestions that's great. If not I could possible try to look at it .. anyhow please update me on the progress

**Comment by jorants** [comment]
just to add, on gentoo i had to download the source of the debian package and make && make install to get dmidecode working.
