### ISSUE TITLE
The webcam is still named VirtualBox Webcam

### ISSUE THREAD

**Issue by corechip** [nsmfoo/antivmdetection#32]
I want to use the webcam, but the traditional usb method does not work. I have to use the webcam passthrough method. https://forums.virtualbox.org/viewtopic.php?f=8&t=74112

After use this, the webcam's name is named VirtualBox Webcam...

Seems I should consider the patching VirtualBox approach... Is threre any easy to use scripts like this?

**Comment by nsmfoo** [comment]
@coreboot2 if you can supply me with the registry key or other location where web camera is called "Virtualbox Webcam"? If so I can see what I can do to help you out

**Comment by nsmfoo** [comment]
@coreboot2 did you resolve this? If so can you share the registry key. It will speed up any implementation on my end =)

**Comment by nsmfoo** [comment]
I took a first look (borrowed a webcam =)) at this issue, did not find an obvious way to fix this (besides modifying the source code). It's a bit sad that VBox needs to prepend everything with "VirtualBox".
That being said I will give spend some more time on this next week.

**Comment by nsmfoo** [comment]
Actually this ended up being more simple then I thought, so using VirtualBox 6.x, if you skip using the command line to attach the camera (I think the docs still states that you must...), anyway boot the VM and insert the Camera (if it's USB), it should show up in the host as the model without "Virtualbox". 

However if you attach it using: "VBoxManage controlvm "<VM NAME>" webcam attach .2" , it will appear as "Virtualbox - <modelname>", confusing.  

This has only been tested on Windows 7.

I think this have to conclude looking at webcam support for now. Please note that I have not looked at getting the webcam to actually work (capturing images etc)
