### ISSUE TITLE
AttributeError: 'module' object has no attribute 'bios' 

### ISSUE THREAD

**Issue by jasoncarr0** [nsmfoo/antivmdetection#33]
As #13

Same issue, everything installed through pip in a virtualenv (and no python anywhere else in the PATH). dmidecode has versions 0.8.1 and 0.9.0 both with the problem 

pip 18.0 from /.../repos/antivmdetection/env/lib/python2.7/site-packages/pip (python 2.7)
Python 2.7.15

I'm booting from UEFI, not BIOS, so that is pretty relevant.

**Comment by jasoncarr0** [comment]
So this is present for bios, baseboard, system, etc.

**Comment by nsmfoo** [comment]
I hope to have a new version available soon that will be using a new dmidecode python module, let see if that one fixed your issue (sorry for the late reply)

**Comment by nsmfoo** [comment]
With the release of 0.1.9 this issue should be resolved. Please check and if needed re-open the issue
