### ISSUE TITLE
Ubuntu 18.04 LTS Issues

### ISSUE THREAD

**Issue by oaustin** [nsmfoo/antivmdetection#35]
I have exactly the same issue... I'm using metal ubuntu 18.04 LTS.
The output of the following: hdparm -i /dev/sda | grep -o 'FwRev=[A-Za-z0-9_+/ ."-]*' | awk -F= '{print $2}'
produces /dev/sda: No such file or directory

_Originally posted by @oaustin in https://github.com/nsmfoo/antivmdetection/issues/23#issuecomment-430330808_

**Comment by oaustin** [comment]
https://github.com/nsmfoo/antivmdetection/issues/23#issuecomment-430330998

**Comment by oaustin** [comment]
Output of my udevadm info -a /dev/nvme0

looking at device '/devices/pci0000:00/0000:00:1d.0/0000:70:00.0/nvme/nvme0':
    KERNEL=="nvme0"
    SUBSYSTEM=="nvme"
    DRIVER==""
    ATTR{cntlid}=="4"
    ATTR{firmware_rev}=="EXD71D1Q"
    ATTR{model}=="PM981 NVMe Samsung 256GB                "
    ATTR{serial}=="      S443NF0K624095"
    ATTR{state}=="live"
    ATTR{subsysnqn}=="nqn.2014.08.org.nvmexpress:144d144d      S443NF0K624095PM981 NVMe Samsung 256GB                "
    ATTR{transport}=="pcie"

  looking at parent device '/devices/pci0000:00/0000:00:1d.0/0000:70:00.0':
    KERNELS=="0000:70:00.0"
    SUBSYSTEMS=="pci"
    DRIVERS=="nvme"
    ATTRS{broken_parity_status}=="0"
    ATTRS{class}=="0x010802"
    ATTRS{consistent_dma_mask_bits}=="64"
    ATTRS{current_link_speed}=="8 GT/s"
    ATTRS{current_link_width}=="4"
    ATTRS{d3cold_allowed}=="1"
    ATTRS{device}=="0xa808"
    ATTRS{dma_mask_bits}=="64"
    ATTRS{driver_override}=="(null)"
    ATTRS{enable}=="1"
    ATTRS{irq}=="16"
    ATTRS{local_cpulist}=="0-11"
    ATTRS{local_cpus}=="fff"
    ATTRS{max_link_speed}=="8 GT/s"
    ATTRS{max_link_width}=="4"
    ATTRS{msi_bus}=="1"
    ATTRS{numa_node}=="0"
    ATTRS{revision}=="0x00"
    ATTRS{subsystem_device}=="0xa801"
    ATTRS{subsystem_vendor}=="0x144d"
    ATTRS{vendor}=="0x144d"

  looking at parent device '/devices/pci0000:00/0000:00:1d.0':
    KERNELS=="0000:00:1d.0"
    SUBSYSTEMS=="pci"
    DRIVERS=="pcieport"
    ATTRS{broken_parity_status}=="0"
    ATTRS{class}=="0x060400"
    ATTRS{consistent_dma_mask_bits}=="32"
    ATTRS{current_link_speed}=="8 GT/s"
    ATTRS{current_link_width}=="4"
    ATTRS{d3cold_allowed}=="1"
    ATTRS{device}=="0xa298"
    ATTRS{dma_mask_bits}=="32"
    ATTRS{driver_override}=="(null)"
    ATTRS{enable}=="1"
    ATTRS{irq}=="124"
    ATTRS{local_cpulist}=="0-11"
    ATTRS{local_cpus}=="fff"
    ATTRS{max_link_speed}=="8 GT/s"
    ATTRS{max_link_width}=="4"
    ATTRS{msi_bus}=="1"
    ATTRS{numa_node}=="-1"
    ATTRS{revision}=="0xf0"
    ATTRS{secondary_bus_number}=="112"
    ATTRS{subordinate_bus_number}=="112"
    ATTRS{subsystem_device}=="0x0859"
    ATTRS{subsystem_vendor}=="0x1028"
    ATTRS{vendor}=="0x8086"

  looking at parent device '/devices/pci0000:00':
    KERNELS=="pci0000:00"
    SUBSYSTEMS==""
    DRIVERS==""


Please assist!

**Comment by nsmfoo** [comment]
Hi, the culprit here is most likely the fact that the script tries to extract information from sda, while your disk is named: "nvme0", if you update the script with "nvme0" and let me know the outcome.  

Regardless I will try to verify the functionality with Ubuntu 18.04

**Comment by oaustin** [comment]
Hi  I've tried to extract information from the disk to no avail... Before replacing it script-wide. Below is my output

sudo hdparm -i /dev/nvme0n1 | grep -o 'Model=[A-Za-z0-9_\+\/ .\"-]*' | awk -F= '{print $2}'
[sudo] password for: 
 HDIO_DRIVE_CMD(identify) failed: Inappropriate ioctl for device
 HDIO_GET_IDENTITY failed: Inappropriate ioctl for device

**Comment by oaustin** [comment]
Hi Mikael,
help!
I was able to get past the initial hurdle by modifying the script in several locations to enable it generate the output to the xxx.sh.  Then in the xxx.sh file make some modifications for strings that were integers.
A pull req could be in order for this all

The latest issue is the "Error: ACPI tables bigger than 64KB (VERR_TOO_MUCH_DATA).

I've gone through your suggestions on prowling.nu [ http://blog.prowling.nu/2012/08/modifying-virtualbox-settings-for.html ] to no avail. I've tried file sizes of : 59KB , 67KB(just to see), my original after the antivm script ran was 160KB+

Thanks,

**Comment by oaustin** [comment]
Hi Mikael,
How do I contribute to this project?

**Comment by oaustin** [comment]
Hi Mikael,
How do I contribute to this project?

**Comment by nsmfoo** [comment]
@oaustin if you have any of the changes that you like me to look at, either do a PR or post the row that you changed to make it work?

**Comment by oaustin** [comment]
> @oaustin if you have any of the changes that you like me to look at, either do a PR or post the row that you changed to make it work?

Hi nsmfoo, PR has been submitted!

**Comment by nsmfoo** [comment]
The issues described in this case and solved in the PR will be included in the next release, except the ACPI issue as it's a Virtualbox limitation

**Comment by nsmfoo** [comment]
Most things should be fixed in 0.1.9, just release. I will close this issue, but feel free to re-open if needed
