### ISSUE TITLE
Configuration error: Querying "DmiBoardSerial" as a string failed (VERR_CFGM_NOT_STRING).

### ISSUE THREAD

**Issue by corownik** [nsmfoo/antivmdetection#36]
Hi Mikael. My host os Ubuntu 16.04, i am try install windows 10 in vbox. After start command [bash p6-2006ru computer] try start guest os for install. After start, i am see this message: 

Configuration error: Querying "DmiBoardSerial" as a string failed (VERR_CFGM_NOT_STRING).

Код ошибки: | NS_ERROR_FAILURE (0x80004005)
-- | --
Компонент: | ConsoleWrap
Интерфейс: | IConsole {872da645-4a9b-1727-bee2-5585105b9eed} 

How i fix it? 

Thank you so much and sorry for my English:)

**Comment by dashjuvi** [comment]
I would like to know too if there's a solution for this

**Comment by dashjuvi** [comment]
> I would like to know too if there's a solution for this

Edit: just go to your "whateveritis.sh" and add at the end of 
VBoxManage setextradata "$1" VBoxInternal/Devices/pcbios/0/Config/DmiBoardSerial	'string: '

the string: part before your number.

**Comment by k41zen** [comment]
Hey,

I've got this issue running a Ubuntu host VM on a MAC with a Windows7 VM inside it. I ran the python script without errors but when I start the VM I get the same error as above. The output of acpidump -s is:

ACPI: MCFG 0x0000000000000000 00003C (v01 PTLTD $PCITBL$ 06040000 LTP 00000001)
ACPI: APIC 0x0000000000000000 000742 (v01 PTLTD ? APIC 06040000 LTP 00000000)
ACPI: BOOT 0x0000000000000000 000028 (v01 PTLTD $SBFTBL$ 06040000 LTP 00000001)
ACPI: WAET 0x0000000000000000 000028 (v01 VMWARE VMW WAET 06040000 VMW 00000001)
ACPI: DSDT 0x0000000000000000 020E9B (v01 PTLTD Custom 06040000 MSFT 03000001)
ACPI: SRAT 0x0000000000000000 0008D0 (v02 VMWARE MEMPLUG 06040000 VMW 00000001)
ACPI: FACP 0x0000000000000000 0000F4 (v04 INTEL 440BX 06040000 PTL 000F4240)
ACPI: HPET 0x0000000000000000 000038 (v01 VMWARE VMW HPET 06040000 VMW 00000001)
ACPI: FACS 0x0000000000000000 000040

Can you help please identifying the part number? If I change the script to print acpi_list_dsdt[4] then its set to "MSFT".

**Comment by nsmfoo** [comment]
This is fixed in the upcoming release, I will go a head and close this case. But if you continue to have the same issue even after the new version, please feel free to re-open the case.
