### ISSUE TITLE
Wrong usage instructions

### ISSUE THREAD

**Issue by jorants** [nsmfoo/antivmdetection#38]
The README.md tells us to run the script and then create computer.lst and user.lst, but then the dependency check fails.

**Comment by nsmfoo** [comment]
Ok need to look at that. In the meanwhile create the above mentioned files, if you look in antivmdetect.py you will find instruction on how to fill these two files. I hope this helps

**Comment by nsmfoo** [comment]
@jorants the README.md will be updated in the up and coming version, thanks for reporting the miss in the instructions!
