### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by CoderDYK** [nsmfoo/antivmdetection#39]
Hi
I am using host Windows 10
and vmware workstation 12 Guest Windows 7

1. Generate script from host
Is it available on Windows 10?

2. Setup VM
The VMware option does not display this feature.
Can I ignore it?

I am a very beginner.
Can you tell me more about how to use it?

**Comment by nsmfoo** [comment]
Hi,

1. The script needs to be run from Linux host to generate the template (it might be possible given that you have the template to apply it from a Windows host, I don't use Windows much so I have not tried, but feel free to explore this option if you have the time)

2. At time moment the template can only be applied to VirtualBox guests
