### ISSUE TITLE
couples of questions 

### ISSUE THREAD

**Issue by Nadacsc** [nsmfoo/antivmdetection#4]
First of all, thank you .. for taking the time to write this script 

I have just a couple of questions : 
1. I've done all the instructions and at the end run the shell passing my vm name , however when I tried to start my vm I've got the following error: 

```
Failed to open a session for the virtual machine ex.

Configuration error: Querying &quot;AcpiCreatorId&quot; as string failed (VERR_CFGM_NOT_STRING).

Result Code: NS_ERROR_FAILURE (0x80004005)
Component: ConsoleWrap
Interface: IConsole {872da645-4a9b-1727-bee2-5585105b9eed}

```
1. do I need to move DevManView.exe to the guest as well with the batch file ?
2. If I want to use it with cuckoo .. is it enough to run the batch file before taking the snapshot or I should put the file with the auto run as you suggested ?

Many thanks for you in advance

**Comment by nsmfoo** [comment]
Hi, 

Let's see, if I can help you out.

1: This error most likely is because of the value that was found is not compatible with VirtualBox, a bit sloppy described. If you have the possibility please do one of the following:
- print the output of the acpi_list[4], just add "print acpi_list[4]" 
- or just send me the output of the following command: acpidump -s
1. No, there no need to move that one, as it's embedded in the batch script. 
2.  You only need to run it before you take the snapshot but as you might take new one later on, having it in the auto run, makes it easier. In essence if the guest reboot, you will need to run the batch script.

Please get back to me so that we can resolve the first issue

/Mikael

**Comment by Nadacsc** [comment]
thanks for your reply:

this is the output of the print command : 
['v01' , 'ACRSYS' , 'ACRPRDCT' , 'F0000000' , '1025' , '00040000' ]

**Comment by nsmfoo** [comment]
Hi,

Can you try and change the AcpiCreatorId row to this and report back if it solved your issue or not?

logfile.write('VBoxManage setextradata "$1" VBoxInternal/Devices/acpi/0/Config/AcpiCreatorId\t\'string:' + acpi_list[4] + '\'\n') 

/Mikael

**Comment by Nadacsc** [comment]
thanks yes this solved the mentioned problem .. and the info of the new vm have changed ..
however I am not sure what the bat file should do 'other than changing the reg keys' because I can still see the unrecognised driver and when I uninstall it manually it says ' found new hardware' and it try to install it again !

**Comment by nsmfoo** [comment]
Sorry for my late reply. There are a few bugs in the current version

"logfile.write(')>fernweh.tmp\r\n')", try to remove the ")" from the corresponding line

Also it might help if you update "logfile.write('echo ' + line)" to look like this  "logfile.write('echo ' + line + '\r\n')"

I hope this helps, I'm working on several new things, which I hope to be finished with by the end of this week

/Mikael

**Comment by nsmfoo** [comment]
A quick update, the DevManView inclusions seems to not work, I will include a fix for that as well.. soon

**Comment by nsmfoo** [comment]
Are you able to verify if the latest commits resolves the issue?

**Comment by nsmfoo** [comment]
Due to lack of feedback, I will close this issue.But please feel free to re-open if the problem still persist

**Comment by k41zen** [comment]
Hey,

I've got this issue running a Ubuntu host VM on a MAC with a Windows7 VM inside it. I ran the python script without errors but when I start the VM I get the same error as above. The output of acpidump -s is: 

ACPI: MCFG 0x0000000000000000 00003C (v01 PTLTD  $PCITBL$ 06040000  LTP 00000001)
ACPI: APIC 0x0000000000000000 000742 (v01 PTLTD  ? APIC   06040000  LTP 00000000)
ACPI: BOOT 0x0000000000000000 000028 (v01 PTLTD  $SBFTBL$ 06040000  LTP 00000001)
ACPI: WAET 0x0000000000000000 000028 (v01 VMWARE VMW WAET 06040000 VMW  00000001)
ACPI: DSDT 0x0000000000000000 020E9B (v01 PTLTD  Custom   06040000 MSFT 03000001)
ACPI: SRAT 0x0000000000000000 0008D0 (v02 VMWARE MEMPLUG  06040000 VMW  00000001)
ACPI: FACP 0x0000000000000000 0000F4 (v04 INTEL  440BX    06040000 PTL  000F4240)
ACPI: HPET 0x0000000000000000 000038 (v01 VMWARE VMW HPET 06040000 VMW  00000001)
ACPI: FACS 0x0000000000000000 000040

Can you help please?
