### ISSUE TITLE
AHCI configuration error: "FirmwareRevision" is longer than 8 bytes (VERR_INVALID_PARAMETER).

### ISSUE THREAD

**Issue by MasterCATZ** [nsmfoo/antivmdetection#40]
Failed to open a session for the virtual machine Z97X-SOCForce.

AHCI configuration error: "FirmwareRevision" is longer than 8 bytes (VERR_INVALID_PARAMETER).

Result Code: | NS_ERROR_FAILURE (0x80004005)
-- | --
Component: | ConsoleWrap
Interface: | IConsole {872da645-4a9b-1727-bee2-5585105b9eed}

looking inside the .vbox file 

`<ExtraDataItem name="VBoxInternal/Devices/ahci/0/Config/Port0/FirmwareRevision" value=" HDIO_GET_IDENTITY failed: Invalid argument"/>
      <ExtraDataItem name="VBoxInternal/Devices/ahci/0/Config/Port0/ModelNumber" value=" HDIO_GET_IDENTITY failed: Invalid argument"/>`

found another error 

`INF_SUCCESS
00:00:00.842093 VMSetError: Configuration error: "AcpiCreatorId" must contain not more than 4 characters`

and another 

`00:00:01.097417 ERROR [COM]: aRC=NS_ERROR_FAILURE (0x80004005) aIID={872da645-4a9b-1727-bee2-5585105b9eed} aComponent={ConsoleWrap} aText={Configuration error: Querying "AcpiCreatorRev" as integer failed (VERR_CFGM_NOT_INTEGER)}, preserve=false aResultDetail=-2106`

starting to think I should have just manually done these unsure how to trim the table back 

`Error: ACPI tables bigger than 64KB (VERR_TOO_MUCH_DATA).`

ls -l /sys/firmware/acpi/tables/ | grep DSDT
-r-------- 1 root root 67136 Feb 12 17:11 DSDT

anyone able to share their CustomTable bin file ? 
http://acpi.sourceforge.net/dsdt/view.php
seems to no longer host them 

<ExtraDataItem name="VBoxInternal/Devices/acpi/0/Config/CustomTable" value="/SnapRaidRW/DATA/VirtualMachines/DSDT_Z97X-SOCForce.bin"/>

sudo apt-get install iasl
sudo cat /sys/firmware/acpi/tables/DSDT > ~/dsdt.dat
iasl -d dsdt.dat
now to burn some brain cells and try and trim some stuff out manually 
iasl -tc /home/<yourusername>/dsdt.dsl

https://www.tonymacx86.com/dsdt-database
or just get some random one from here 

[Z97X-SOCForce.zip](https://github.com/nsmfoo/antivmdetection/files/2854606/Z97X-SOCForce.zip)

**Comment by nsmfoo** [comment]
With the release of 0.1.9 I hope this issue is no more, please test and verify. Re-open this case if needed.
