### ISSUE TITLE
Error reading custom ACPI table. (VERR_PATH_NOT_FOUND)

### ISSUE THREAD

**Issue by anilplp** [nsmfoo/antivmdetection#45]
When I exported image in ova file and tried to run in another machine I got the below error.

Error reading custom ACPI table. (VERR_PATH_NOT_FOUND).   Result Code:  E_FAIL (0x80004005) Component:  ConsoleWrap Interface:  IConsole {872da645-4a9b-1727-bee2-5585105b9eed}
VirtualBox Logs:
00:00:02.259913 ACPI: Reading custom ACPI table(0) from file '/home/nav/Desktop/antivm/DSDT_OptiPlex9020.bin' (0 bytes)
00:00:02.259924 VMSetError: F:\tinderbox\win-6.0\src\VBox\Devices\PC\DevACPI.cpp(4013) int __cdecl acpiR3Construct(struct PDMDEVINS *,int,struct CFGMNODE *); rc=VERR_PATH_NOT_FOUND
00:00:02.259929 VMSetError: Error reading custom ACPI table.
00:00:02.259937 PDM: Failed to construct 'acpi'/0! VERR_PATH_NOT_FOUND (-103) - Path not found.

How to run the imgae in other machines?

Do I have to run the script in that machine also?

**Comment by ThisIsNotMalware** [comment]
Just run this: 

VBoxManage.exe setextradata REPLACEME1 VBoxInternal/Devices/acpi/0/Config/CustomTable C:\Users\SOMETHING\SOMETHING\REPLACEME2.bin

were REPLACEME1: name of your vm and REPLACEME2: name of your ACPI tables

hope that helps

**Comment by nsmfoo** [comment]
@anilplp did the suggestion that @ThisIsNotMalware fix the issue?

**Comment by anilplp** [comment]
Apologies for late reply
 @ThisIsNotMalware  that commmand worked fine.
@nsmfoo yes it fixed the issue

**Comment by nsmfoo** [comment]
@anilplp  no apologies needed, I'm a master of slow responses myself ;)

Great, then I will close this case

**Comment by alanjsebas** [comment]
How do you run this command in linux?

**Comment by gemfield** [comment]
@alanjsebas Just use vboxmanage command. See https://github.com/DeepVAC/MLab/issues/61
