### ISSUE TITLE
windows 10 x64 acpi bios error

### ISSUE THREAD

**Issue by gianlucadandrea** [nsmfoo/antivmdetection#46]
hi, after executing the .sh script to modify some vbox parameters, windows 10 x64 cannot be installed. the error is ACPI BIOS ERROR very early in the installation process.

commenting out the VBoxInternal/Devices/acpi/0/Config/CustomTable line in the vbox, windows 10 x64 gets installed correctly, so the problem I think is using the dumped DSDT table

**Comment by ThisIsNotMalware** [comment]
Can you post the error?

You might want to check the VT-x enabled in your BIOS to use virtualization

**Comment by nsmfoo** [comment]
@gianlucadandrea Are you able to add the error message?

**Comment by nsmfoo** [comment]
I will go a head and close this case, feel free to re-open if needed.
