### ISSUE TITLE
Online Test

### ISSUE THREAD

**Issue by cod3r-dev** [nsmfoo/antivmdetection#47]
There is any online site (JavaScript perhaps) to check / dedect virtual machine / browser ?

**Comment by nsmfoo** [comment]
Hi @dimitri0us,  Not to my knowledge, but maybe someone else knows? That being said Javascript have limited access to hardware information, so I'm not sure it can be done  (there has been bugs in browsers that allowed to much HW info to be read, but bugs get fixed)

**Comment by nsmfoo** [comment]
@dimitri0us  just by a chance I found this one today from @bannedit: https://bannedit.github.io/Virtual-Machine-Detection-In-The-Browser.html#Virtual-Machine-Detection-In-The-Browser . 

No tested, but I think this was what you where asking for..

**Comment by nsmfoo** [comment]
I will close this case, feel free to re-open if needed.
