### ISSUE TITLE
NameError: name 'v' is not defined

### ISSUE THREAD

**Issue by Mart1neZ** [nsmfoo/antivmdetection#48]
I get this error when running the script:

Traceback (most recent call last):
  File "antivmdetect.py", line 50, in <module>
    dmi_info['DmiBIOSReleaseDate'] =  "string:" + v['Relase Date']
NameError: name 'v' is not defined

**Comment by nsmfoo** [comment]
Hi @Mart1neZ 

* Lets try this:
- Do you get a "Release date" in the output from the following command; sudo dmidecode -t0 ?

* Also:
- Are you running version 1.9? 
- Can you send the output of: pip3 list | grep py-dmidecode ?

I think this is a good start
/Mikael

**Comment by nsmfoo** [comment]
@Mart1neZ Did you get a chance to try the above?

**Comment by roohat** [comment]
Yeap, that's what you get when you don't specify version of library you depend in `requirements.txt`. Things will break when your library decided to push breaking changes.

```python
import dmidecode
```

should changed to this:

```python
from dmidecode import DMIDecode
dmidecode = DMIDecode()
```

I'll be soon open a pull request with this issue fixed once I finished testing it.
