### ISSUE TITLE
vm on game

### ISSUE THREAD

**Issue by bumblebee2511** [nsmfoo/antivmdetection#50]
This is used to vmware pass virtual honestly right? I read but did not understand how to
Install dependencies sudo apt install python3-pip libcdio-utils acpica-tools mesa-utils
Install Python modules: pip3 install -r requirements.txt
Can you help me not to thank.

**Comment by NisarHotac** [comment]
the pip3 install -r requirment.txt is a file in a folder which you download the ffolder is called antivmdetection-master 
 install python 3.8.2 and then install pip3 google it 
after open cmd go to the antivmdetection-master directory and type this command "pip3 install -r requirements.txt" should work only if you installed python and pip3 after python

**Comment by nsmfoo** [comment]
@bumblebee2511  did the response from @NisarHotac answer your question? If not please let me know

**Comment by nsmfoo** [comment]
Any update on this one? If not I will close it .. in a day or two

**Comment by nsmfoo** [comment]
I will go a head and close this case, please re-open it or create a new one if needed

**Comment by bumblebee2511** [comment]
I'm back can you make a video tutorial on it, thanks
