### ISSUE TITLE
Trouble installing W10 guest on Mac

### ISSUE THREAD

**Issue by mngyuan** [nsmfoo/antivmdetection#53]
I've generated the script using a LiveUSB of Ubuntu 20.04 and rebooted into MacOS. I'm getting the following when running `./MacBookPro11_3.sh test`
```
VBoxManage: error: Invalid MAC address format
VBoxManage: error: Details: code NS_ERROR_INVALID_ARG (0x80070057), component NetworkAdapterWrap, interface INetworkAdapter, callee nsISupports
VBoxManage: error: Context: "COMSETTER(MACAddress)(Bstr(ValueUnion.psz).raw())" at line 2068 of file VBoxManageModifyVM.cpp
```

and the W10 guest is giving me the BSOD with Stop Code ACPI Bios Error on booting the W10 install dvd.

I modified the relevant line in `MacBookPro11_3.sh` to have an even first byte of the MAC address (not sure why this is happening):
```diff
- VBoxManage modifyvm "$1" --macaddress1  e58a54e0fdca
+ VBoxManage modifyvm "$1" --macaddress1  e68a54e0fdca
```

and recreated the guest in VirtualBox, but it's still repeatedly crashing when the W10 install tries to load up. The W10 install DVD boots fine if I don't run the script. 

The only setting I wasn't sure about from the README was the Host Network Manager - I have the vboxnet0 adapter set to Configure Adapter Manually -> 192.168.56.1/24 and DHCP enabled - and the Storage. I have one SATA Storage controller with my `vdi` file in the first slot and the W10 install DVD in the second slot.

Not sure how to proceed - let me know if I should post the script (is that safe?)

**Comment by mngyuan** [comment]
I worked around this by downloading an existing W10 ova from Microsoft and running my script on that machine.

**Comment by nsmfoo** [comment]
@mngyuan the MAC address thing, is actually something I do remember having seen before. So the script takes the real MAC address and based on that one generates one similar to the original. Sometimes the generation seems to generate a none valid MAC. I will make a mental node to look at it.

The "alert" for the standard VBox IP-range is just a soft alert and can be ignored. At least in test =)

If you look in the generated template shell script, some values might have been replaced with "*" these are for manual editing as the script was not fully able to guess the value.

I think I need to revisit this script shortly

**Comment by mngyuan** [comment]
no worries, I'm past the vm detection for the game I'm playing. a pafish run is coming up with some VirtualBox artifacts but that might be my fault for installing the guest add-ons. thanks for your hard work!
