### ISSUE TITLE
DevManView.exe /uninstall "PCI\VEN_80EE&DEV_CAFE"* /use_wildcard

### ISSUE THREAD

**Issue by pabraksas** [nsmfoo/antivmdetection#6]
Hello!
DevManView.exe /uninstall "PCI\VEN_80EE&DEV_CAFE"\* /use_wildcard
It's cool!! 
But VBox contains also another device: "PCI\VEN_80EE&DEV_BEEF", and 
DevManView.exe /uninstall "PCI\VEN_80EE&DEV_BEEF"\* /use_wildcard
not work =(

**Comment by nsmfoo** [comment]
I'm sorry for the late reply. Currently I'm not aware or able to remove that device. If you compile your own version of VBox then you can solve it. But so far it's out of the scoop (for me) as the aim is to use the stock installation
