### ISSUE TITLE
Keyerror due to typo

### ISSUE THREAD

**Issue by adindrabkin** [nsmfoo/antivmdetection#60]
Line 50 says `   dmi_info['DmiBIOSReleaseDate'] =  "string:" + v['Relase Date']` when it should say 
`dmi_info['DmiBIOSReleaseDate'] =  "string:" + v['Release Date']`

Also, py-dmidecode does not have get_by_type. I found this repo that has it, however https://github.com/345813473/py-dmidecode

**Comment by nsmfoo** [comment]
@adindrabkin what looks like a typo .. it is actually not a typo, ages ago there were a dmidecode release, that contained the typo, which I had to handle. However as this is not the first time someone opens a case to point that out. I will add a comment in the code and look to remove the check in a future release. 

https://pypi.org/project/py-dmidecode/0.0.2/#files <-- which is the version stated in the requirements.txt as the version to use. That being said, it might be a good time to look at using the latest version 0.1.0, which have a newer syntax

/Mikael

**Comment by nsmfoo** [comment]
Closing this as a clarification was added previously (https://github.com/nsmfoo/antivmdetection/commit/11d06a45b0d771501caf6b2d95999956a3ce60f8). However a code review is needed also look to move to a never version of py-dmidecode
