### ISSUE TITLE
Add check for acpidump version used

### ISSUE THREAD

**Issue by Antelox** [nsmfoo/antivmdetection#7]
If it's used an old version of acpidump, for example the one in Ubuntu 12.04, "-s" command line argument doesn't exist so the python script will build bash and powershell scripts with wrong parameters for .vbox file settings as well as for registry names that must be changed inside the guest.

Possible solution:

if "invalid option --'s'" in acpi_misc:
    print "You have an old version of acpidump. Please upgrade it or use a
Linux distro => 14.04!"
else:
    acpi_list = acpi_misc.split(' ')
    acpi_list = filter(None, acpi_list)

**Comment by nsmfoo** [comment]
Yet another good find. Fix will be included in the next release, thanks!

**Comment by nsmfoo** [comment]
If possible, please try the new release and let me know if it solved the issue you reported
