### ISSUE TITLE
CreationTime error in the powershell script

### ISSUE THREAD

**Issue by Antelox** [nsmfoo/antivmdetection#8]
This is the error that I got when I execute the ps1 script inside the guest.

Exception setting "CreationTime": "Cannot convert value "23/07/2008 6.00" to type "System.DateTime". Error: "String was
 not recognized as a valid DateTime.""
At C:\Users\PC\Desktop\SystemProductName.ps1:5546 char:45
-  Get-ChildItem $location$namely$ext | % {$_. <<<< CreationTime = RandomDate }
  - CategoryInfo          : InvalidOperation: (:) [], RuntimeException
  - FullyQualifiedErrorId : PropertyAssignmentException

Exception setting "LastWriteTime": "Cannot convert value "15/04/2010 4.27" to type "System.DateTime". Error: "String wa
s not recognized as a valid DateTime.""
At C:\Users\PC\Desktop\SystemProductName.ps1:5547 char:45
-  Get-ChildItem $location$namely$ext | % {$_. <<<< LastWriteTime = RandomDate }
  - CategoryInfo          : InvalidOperation: (:) [], RuntimeException
  - FullyQualifiedErrorId : PropertyAssignmentException

Any hints/solutions? Thanks in advance.

**Comment by nsmfoo** [comment]
Thank you for your report, much appreciated! A re-worked function will be included in the next release

**Comment by nsmfoo** [comment]
If possible, please try the new release and let me know if it solved the issue you reported
