### ISSUE TITLE
NameError name v is not defined

### ISSUE THREAD

**Issue by hexlax** [nsmfoo/antivmdetection#9]
I'm seeing the current error:

`
$ python antivmdetect.py 
--- Generate VirtualBox templates to help thwart VM detection and more .. - Mikael, @nsmfoo ---
[*] Creating VirtualBox modifications ..
Traceback (most recent call last):
  File "antivmdetect.py", line 45, in <module>
    dmi_info['DmiBIOSReleaseDate'] = v['data']['Relase Date']
NameError: name 'v' is not defined
`

Here is my output from "sudo dmidecode -t 0":

dmidecode 2.12
SMBIOS 2.8 present.

Handle 0x0000, DMI type 0, 24 bytes
BIOS Information
	Vendor: American Megatrends Inc.
	Version: 1.0b
	Release Date: 04/21/2015
	Address: 0xF0000
	Runtime Size: 64 kB
	ROM Size: 16384 kB
	Characteristics:
		PCI is supported
		BIOS is upgradeable
		BIOS shadowing is allowed
		Boot from CD is supported
		Selectable boot is supported
		BIOS ROM is socketed
		EDD is supported
		5.25"/1.2 MB floppy services are supported (int 13h)
		3.5"/720 kB floppy services are supported (int 13h)
		3.5"/2.88 MB floppy services are supported (int 13h)
		Print screen service is supported (int 5h)
		8042 keyboard services are supported (int 9h)
		Serial services are supported (int 14h)
		Printer services are supported (int 17h)
		ACPI is supported
		USB legacy is supported
		BIOS boot specification is supported
		Targeted content distribution is supported
		UEFI is supported
	BIOS Revision: 5.6

**Comment by Antelox** [comment]
Try in a python shell what you get from this -> dmidecode.bios().values()
That is, try to play a bit with the code where you got the error running it in the python shell to see what go wrong.

**Comment by hexlax** [comment]
I ended up removing most of the dmidecode stuff and placed hard values in dmi_info[]

Works great! I have the same results now in pafish.

**Comment by nsmfoo** [comment]
Late response, I will see if I can fix the issue. But I'm glad that hard values worked out as well in the meantime.
